[2022-12-09T07:54:28.038+0000] {processor.py:153} INFO - Started process (PID=52) to work on /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:54:28.038+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/bertopic_autopik_airflow.py for tasks to queue
[2022-12-09T07:54:28.039+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:54:28.039+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:54:28.857+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:54:28.855+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/bertopic_autopik_airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bertopic_autopik_airflow.py", line 19, in <module>
    from functions import  data, training_bertopic
  File "/opt/airflow/dags/functions/training_bertopic.py", line 12, in <module>
    from bertopic import BERTopic
ModuleNotFoundError: No module named 'bertopic'
[2022-12-09T07:54:28.857+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:54:28.890+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/bertopic_autopik_airflow.py took 0.857 seconds
[2022-12-09T07:54:59.328+0000] {processor.py:153} INFO - Started process (PID=59) to work on /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:54:59.329+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/bertopic_autopik_airflow.py for tasks to queue
[2022-12-09T07:54:59.330+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:54:59.330+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:54:59.879+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:54:59.878+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/bertopic_autopik_airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bertopic_autopik_airflow.py", line 19, in <module>
    from functions import  data, training_bertopic
  File "/opt/airflow/dags/functions/training_bertopic.py", line 12, in <module>
    from bertopic import BERTopic
ModuleNotFoundError: No module named 'bertopic'
[2022-12-09T07:54:59.880+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:54:59.911+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/bertopic_autopik_airflow.py took 0.587 seconds
[2022-12-09T07:55:30.652+0000] {processor.py:153} INFO - Started process (PID=66) to work on /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:55:30.653+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/bertopic_autopik_airflow.py for tasks to queue
[2022-12-09T07:55:30.654+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:55:30.654+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:55:31.159+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:55:31.158+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/bertopic_autopik_airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bertopic_autopik_airflow.py", line 19, in <module>
    from functions import  data, training_bertopic
  File "/opt/airflow/dags/functions/training_bertopic.py", line 12, in <module>
    from bertopic import BERTopic
ModuleNotFoundError: No module named 'bertopic'
[2022-12-09T07:55:31.160+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:55:31.195+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/bertopic_autopik_airflow.py took 0.547 seconds
[2022-12-09T07:56:01.888+0000] {processor.py:153} INFO - Started process (PID=73) to work on /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:56:01.889+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/bertopic_autopik_airflow.py for tasks to queue
[2022-12-09T07:56:01.890+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:56:01.890+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:56:02.432+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:56:02.431+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/bertopic_autopik_airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bertopic_autopik_airflow.py", line 19, in <module>
    from functions import  data, training_bertopic
  File "/opt/airflow/dags/functions/training_bertopic.py", line 12, in <module>
    from bertopic import BERTopic
ModuleNotFoundError: No module named 'bertopic'
[2022-12-09T07:56:02.433+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:56:02.456+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/bertopic_autopik_airflow.py took 0.571 seconds
[2022-12-09T07:56:33.144+0000] {processor.py:153} INFO - Started process (PID=80) to work on /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:56:33.145+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/bertopic_autopik_airflow.py for tasks to queue
[2022-12-09T07:56:33.145+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:56:33.145+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:56:33.642+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:56:33.641+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/bertopic_autopik_airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bertopic_autopik_airflow.py", line 19, in <module>
    from functions import  data, training_bertopic
  File "/opt/airflow/dags/functions/training_bertopic.py", line 12, in <module>
    from bertopic import BERTopic
ModuleNotFoundError: No module named 'bertopic'
[2022-12-09T07:56:33.643+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:56:33.672+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/bertopic_autopik_airflow.py took 0.532 seconds
[2022-12-09T07:57:04.285+0000] {processor.py:153} INFO - Started process (PID=86) to work on /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:57:04.295+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/bertopic_autopik_airflow.py for tasks to queue
[2022-12-09T07:57:04.296+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:57:04.295+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:57:04.882+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:57:04.881+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/bertopic_autopik_airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bertopic_autopik_airflow.py", line 19, in <module>
    from functions import  data, training_bertopic
  File "/opt/airflow/dags/functions/training_bertopic.py", line 12, in <module>
    from bertopic import BERTopic
ModuleNotFoundError: No module named 'bertopic'
[2022-12-09T07:57:04.883+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:57:04.910+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/bertopic_autopik_airflow.py took 0.628 seconds
[2022-12-09T07:57:35.107+0000] {processor.py:153} INFO - Started process (PID=93) to work on /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:57:35.117+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/bertopic_autopik_airflow.py for tasks to queue
[2022-12-09T07:57:35.118+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:57:35.118+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:57:35.780+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:57:35.778+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/bertopic_autopik_airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bertopic_autopik_airflow.py", line 19, in <module>
    from functions import  data, training_bertopic
  File "/opt/airflow/dags/functions/training_bertopic.py", line 12, in <module>
    from bertopic import BERTopic
ModuleNotFoundError: No module named 'bertopic'
[2022-12-09T07:57:35.780+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:57:35.810+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/bertopic_autopik_airflow.py took 0.707 seconds
[2022-12-09T07:58:06.026+0000] {processor.py:153} INFO - Started process (PID=100) to work on /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:58:06.037+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/bertopic_autopik_airflow.py for tasks to queue
[2022-12-09T07:58:06.038+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:58:06.038+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:58:06.704+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:58:06.702+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/bertopic_autopik_airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bertopic_autopik_airflow.py", line 19, in <module>
    from functions import  data, training_bertopic
  File "/opt/airflow/dags/functions/training_bertopic.py", line 12, in <module>
    from bertopic import BERTopic
ModuleNotFoundError: No module named 'bertopic'
[2022-12-09T07:58:06.704+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:58:06.735+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/bertopic_autopik_airflow.py took 0.715 seconds
[2022-12-09T07:58:36.968+0000] {processor.py:153} INFO - Started process (PID=108) to work on /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:58:36.970+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/bertopic_autopik_airflow.py for tasks to queue
[2022-12-09T07:58:36.971+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:58:36.971+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:58:37.621+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:58:37.619+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/bertopic_autopik_airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bertopic_autopik_airflow.py", line 19, in <module>
    from functions import  data, training_bertopic
  File "/opt/airflow/dags/functions/training_bertopic.py", line 12, in <module>
    from bertopic import BERTopic
ModuleNotFoundError: No module named 'bertopic'
[2022-12-09T07:58:37.622+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:58:37.655+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/bertopic_autopik_airflow.py took 0.692 seconds
[2022-12-09T07:59:08.282+0000] {processor.py:153} INFO - Started process (PID=115) to work on /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:59:08.292+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/bertopic_autopik_airflow.py for tasks to queue
[2022-12-09T07:59:08.293+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:59:08.292+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:59:08.864+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:59:08.863+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/bertopic_autopik_airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bertopic_autopik_airflow.py", line 19, in <module>
    from functions import  data, training_bertopic
  File "/opt/airflow/dags/functions/training_bertopic.py", line 12, in <module>
    from bertopic import BERTopic
ModuleNotFoundError: No module named 'bertopic'
[2022-12-09T07:59:08.865+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:59:08.899+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/bertopic_autopik_airflow.py took 0.621 seconds
[2022-12-09T07:59:39.414+0000] {processor.py:153} INFO - Started process (PID=143) to work on /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:59:39.424+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/bertopic_autopik_airflow.py for tasks to queue
[2022-12-09T07:59:39.425+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:59:39.425+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:59:40.060+0000] {logging_mixin.py:137} INFO - [2022-12-09T07:59:40.058+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/bertopic_autopik_airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bertopic_autopik_airflow.py", line 19, in <module>
    from functions import  data, training_bertopic
  File "/opt/airflow/dags/functions/training_bertopic.py", line 12, in <module>
    from bertopic import BERTopic
ModuleNotFoundError: No module named 'bertopic'
[2022-12-09T07:59:40.060+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/bertopic_autopik_airflow.py
[2022-12-09T07:59:40.091+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/bertopic_autopik_airflow.py took 0.680 seconds
